---
abstract: 'Very fast parser of XML document into nested arrays'
author:
  - 'Petr Pajas <pajas@matfyz.cz>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.150005'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-CompactTree-XS
no_index:
  directory:
    - t
    - inc
requires:
  Test::Simple: '0'
  XML::LibXML: '1.68'
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
